// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Atiqur Rahman Asif's professional profile summary, contact info, and skills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Atiqur Rahman Asif",
      roles: ["IT Professional", "Marketing Strategist"],
      location: "Savar, Dhaka-1344, Bangladesh",
      email: "atiq.asif260@gmail.com",
      phone: "+880 1999 443965",
      website: "https://atiqurrahman-asif.lovable.app",
      socials: {
        linkedin: "https://www.linkedin.com/in/atiqurrahman-asif/",
        github: "https://github.com/atiqasif260",
        instagram: "https://www.instagram.com/atiq.asif260/"
      },
      skills: {
        technical: ["System Administration", "Networking (LAN/WAN)", "Server Management", "Security Protocols", "SAP BTP"],
        professional: ["Strategic Planning", "Project Management", "Vendor Management", "Budgeting"]
      }
    };
    void z;
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List experience",
  description: "Return Atiqur Rahman Asif's professional experience history.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const experience = [
      {
        period: "04/2023 \u2014 Present",
        title: "Executive, IT Department",
        company: "Ztrios Technologies LTD",
        highlights: [
          "System administration across networks and software",
          "Strategic planning aligning IT with business goals",
          "Security policies and data integrity",
          "Vendor management and IT budgeting",
          "Leading IT projects and system migrations"
        ]
      },
      {
        period: "02/2022 \u2014 03/2023",
        title: "Jr. Executive, IT Department",
        company: "Circle Network",
        highlights: [
          "LAN/WAN networking and server management",
          "Security protocols and data backups",
          "User hardware/software support"
        ]
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
      structuredContent: { experience }
    };
  }
});

// src/lib/mcp/tools/list-education.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_education_default = defineTool3({
  name: "list_education",
  title: "List education",
  description: "Return Atiqur Rahman Asif's education and certifications.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const education = [
      { year: "2021", degree: "B.Tech in Computer Science & Engineering", institution: "Lovely Professional University (LPU)", detail: "CGPA: 3.75/4.00" },
      { year: "2017", degree: "Higher Secondary School Certificate", institution: "Savar Model College", detail: "Science \u2014 GPA 3.83" },
      { year: "2015", degree: "Secondary School Certificate", institution: "Savar Cantonment Board Boys High School", detail: "Science \u2014 GPA 4.29" }
    ];
    const certifications = [
      { title: "Cyber Security Certificate", issuer: "Google.org" },
      { title: "SAP Business Technology Platform (BTP)", issuer: "SAP Sapphire" }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify({ education, certifications }, null, 2) }],
      structuredContent: { education, certifications }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var send_message_default = defineTool4({
  name: "send_message",
  title: "Send a message",
  description: "Record a message from the signed-in user for Atiq. Useful for AI clients relaying an intro or opportunity.",
  inputSchema: {
    subject: z2.string().min(1).describe("Short subject line."),
    body: z2.string().min(1).describe("The message body.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: ({ subject, body }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const record = {
      from: { user_id: ctx.getUserId(), email: ctx.getUserEmail() },
      subject,
      body,
      received_at: (/* @__PURE__ */ new Date()).toISOString()
    };
    console.log("[mcp] send_message", record);
    return {
      content: [{ type: "text", text: `Message received. Atiq can reach you at ${ctx.getUserEmail() ?? "your account email"}.` }],
      structuredContent: { ok: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lddsmrmonowemkmkdnfq";
var mcp_default = defineMcp({
  name: "atiq-portfolio-mcp",
  title: "Atiq Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for Atiqur Rahman Asif's portfolio. Use get_profile, list_experience, and list_education to answer questions about Atiq. Use send_message to relay a note from the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_experience_default, list_education_default, send_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
